package com.firstapp.firstappbackend.pojo;

import java.util.Date;

public class ChangeLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_log.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_log.note_id
     *
     * @mbg.generated
     */
    private Integer noteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_log.operation
     *
     * @mbg.generated
     */
    private String operation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_log.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_log.id
     *
     * @return the value of change_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_log.id
     *
     * @param id the value for change_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_log.user_id
     *
     * @return the value of change_log.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_log.user_id
     *
     * @param userId the value for change_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_log.note_id
     *
     * @return the value of change_log.note_id
     *
     * @mbg.generated
     */
    public Integer getNoteId() {
        return noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_log.note_id
     *
     * @param noteId the value for change_log.note_id
     *
     * @mbg.generated
     */
    public void setNoteId(Integer noteId) {
        this.noteId = noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_log.operation
     *
     * @return the value of change_log.operation
     *
     * @mbg.generated
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_log.operation
     *
     * @param operation the value for change_log.operation
     *
     * @mbg.generated
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_log.update_time
     * @return the value of change_log.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_log.update_time
     * @param updateTime the value for change_log.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}