package com.firstapp.firstappbackend.dao;

import com.firstapp.firstappbackend.pojo.Change;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ChangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Change
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("noteId") Integer noteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Change
     *
     * @mbg.generated
     */
    int insert(Change record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Change
     *
     * @mbg.generated
     */
    Change selectByPrimaryKey(@Param("id") Integer id, @Param("noteId") Integer noteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Change
     *
     * @mbg.generated
     */
    List<Change> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Change
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Change record);
}