
spring:
  servlet:
    session:
      timeout: 3600s
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://161.97.110.236:3306/NotesApp?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: bushu123
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
mybatis:
  mapper-locations: classpath*:com/firstapp/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml


